# Generated by Django 5.0.3 on 2024-04-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'permissions': [('create_song', 'Can create a song')]},
        ),
    ]
