# Generated by Django 5.0.3 on 2024-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='non_owner_visible',
            field=models.BooleanField(default=True),
        ),
    ]
