# Generated by Django 5.0.3 on 2024-04-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_song_non_owner_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
