# Generated by Django 5.0.3 on 2024-04-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_userlibrary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'permissions': [('add_to_library', 'Can add a song to library')]},
        ),
    ]
