# Generated by Django 5.0.3 on 2024-04-05 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_alter_song_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlibrary',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userlibrary',
            name='private',
        ),
    ]
