# Generated by Django 5.0.3 on 2024-04-10 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0015_alter_audio_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='song',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='core_api.song'),
        ),
    ]
