# Generated by Django 5.0.3 on 2024-04-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0016_alter_audio_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='song',
        ),
    ]
