# Generated by Django 5.0.3 on 2024-04-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0019_audio_song_userfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'permissions': [('add_to_favorites', 'Can add a song to favorites')]},
        ),
    ]
