# Generated by Django 5.0.3 on 2024-04-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0020_alter_song_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['published_at'], 'permissions': [('add_to_favorites', 'Can add a song to favorites')]},
        ),
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'verbose_name_plural': 'User libraries'},
        ),
    ]
