# Generated by Django 5.0.3 on 2024-04-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0024_audio_uploaded_by_alter_audio_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='end_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='start_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
