# Generated by Django 5.0.3 on 2024-04-30 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0025_comment_end_time_comment_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time_range',
        ),
    ]
