# Generated by Django 5.0.3 on 2024-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0026_remove_comment_time_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
